apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: fluentd
data:
  fluentd.conf: |-
    @include pods-kind-test-fluent.conf
  pods-kind-test-fluent.conf: |-
    <source>
      @type tail
      read_from_head true
      tag kubernetes-kind.*
      path /var/log/containers/*.log
      exclude_path ["/var/log/containers/fluent*"]
    </source>
  #elastic-conf